# API redirects
## Proxy cases endpoint directly to external API
[[redirects]]
  from = "/api/buzzard/"
  to = "https://buzzard.org/ukraine.php"
  status = 200
  force = true
  
[[redirects]]
  from = "/cors-proxy/*"
  to = ":splat"
  status = 200
  force = true
